services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:3.13
    volumes:
      - ../..:/workspaces:cached
    #    network_mode: service:db
    command: sleep infinity
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5433
      - POSTGRES_DB=mathe
      - POSTGRES_USER=provdemo
      - POSTGRES_PASSWORD=provdemo
      - POSTGRES_TIMESCALE_HOST=postgres
      - POSTGRES_TIMESCALE_PORT=5432
    depends_on:
      # Ensures that the databases are started before the API
      postgres:
        condition: service_healthy

  # --- PostgreSQL Service with ProvSQL compiled from source ---
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5433:5433"
    volumes:
      - palimpzest_tryout_postgres_data:/var/lib/postgresql/data
      - ../assets/postgres-seed:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=provdemo
      - POSTGRES_PASSWORD=provdemo
      - POSTGRES_DB=mathe
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U provdemo -d mathe" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  palimpzest_tryout_postgres_data:
